# Generated by Django 3.1.3 on 2020-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MostCheapBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20, null=True)),
                ('country_name', models.CharField(max_length=20, null=True)),
                ('buy', models.FloatField(null=True)),
                ('buy_fee_rate', models.CharField(max_length=30, null=True)),
                ('sell', models.FloatField(null=True)),
                ('sell_fee_rate', models.CharField(max_length=30, null=True)),
                ('trading_rate', models.FloatField(null=True)),
                ('update_date', models.DateField()),
            ],
        ),
    ]
