# Generated by Django 3.1.3 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xgboostinfo',
            name='dollar_close',
            field=models.CharField(max_length=30, null=True, verbose_name='달러 종가'),
        ),
    ]
