# Generated by Django 3.1.3 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0001_initial'),
    ]

    operations = [
    ]
