# Generated by Django 3.1.3 on 2020-11-13 07:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverNews',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='뉴스 제목')),
                ('link', models.TextField(max_length=200, null=True, verbose_name='링크')),
                ('news_company', models.CharField(max_length=30, null=True, verbose_name='신문사')),
                ('contents', models.TextField(max_length=builtins.max, verbose_name='내용')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '환율 기사',
                'verbose_name_plural': '환율 기사',
                'db_table': 'NaverNews',
            },
        ),
    ]
