# Generated by Django 3.1.3 on 2020-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mostcheapbank',
            options={'verbose_name': '국내환율', 'verbose_name_plural': '국내환율'},
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='bank_name',
            field=models.CharField(max_length=20, null=True, verbose_name='은행이름'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='buy',
            field=models.FloatField(null=True, verbose_name='현찰 살 때'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='buy_fee_rate',
            field=models.CharField(max_length=30, null=True, verbose_name='수수료율'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='country_name',
            field=models.CharField(max_length=20, null=True, verbose_name='외화'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='sell',
            field=models.FloatField(null=True, verbose_name='현찰 팔 때'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='sell_fee_rate',
            field=models.CharField(max_length=30, null=True, verbose_name='수수료율'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='trading_rate',
            field=models.FloatField(null=True, verbose_name='매매기준율'),
        ),
        migrations.AlterField(
            model_name='mostcheapbank',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='등록날짜'),
        ),
        migrations.AlterModelTable(
            name='mostcheapbank',
            table='은행별 환율 테이블',
        ),
    ]
