# Generated by Django 3.1.3 on 2020-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0002_navernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='navernews',
            name='craw_date',
            field=models.CharField(max_length=30, null=True, verbose_name='뉴스 날자'),
        ),
        migrations.AlterField(
            model_name='navernews',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='크롤링 날자'),
        ),
    ]
