# Generated by Django 3.1.3 on 2020-11-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0002_auto_20201111_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignbank',
            name='jpy_to_local_money',
        ),
        migrations.RemoveField(
            model_name='foreignbank',
            name='usd_to_local_money',
        ),
    ]
