# Generated by Django 3.1.3 on 2020-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0002_auto_20201124_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xgboostinfo',
            name='dollar_close',
            field=models.FloatField(null=True, verbose_name='달러 종가'),
        ),
    ]
