# Generated by Django 3.1.3 on 2020-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0003_auto_20201113_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('bank_code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='은행코드')),
                ('bank_name', models.CharField(max_length=20, null=True, verbose_name='은행명')),
                ('bank_logo', models.CharField(max_length=20, null=True, verbose_name='은행로고')),
            ],
            options={
                'verbose_name': '은행 정보',
                'verbose_name_plural': '은행 정보',
                'db_table': 'Bank_Info',
            },
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('country_name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='나라이름(영어)')),
                ('country_flag', models.CharField(max_length=10, null=True, verbose_name='국기')),
                ('name_kor', models.CharField(max_length=10, null=True, verbose_name='나라이름(한국어)')),
            ],
            options={
                'verbose_name': '나라 정보',
                'verbose_name_plural': '나라 정보',
                'db_table': 'Country_Info',
            },
        ),
    ]
