# Generated by Django 3.1.1 on 2020-11-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0003_auto_20201113_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaverNews',
        ),
    ]
