# Generated by Django 3.1.3 on 2020-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0003_auto_20201120_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='XGBoostInfo',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30, verbose_name='날짜')),
                ('dollar_close', models.FloatField(null=True, verbose_name='달러 종가')),
            ],
            options={
                'verbose_name': 'XGboost예측테이블',
                'verbose_name_plural': 'XGboost예측테이블',
                'db_table': 'XGBoost_Info',
            },
        ),
    ]
