# Generated by Django 3.1.3 on 2020-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0003_auto_20201124_2012'),
    ]

    operations = [

    ]
