# Generated by Django 3.1.1 on 2020-11-19 03:01

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0004_delete_navernews'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverNews',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='뉴스 제목')),
                ('link', models.TextField(max_length=200, null=True, verbose_name='링크')),
                ('company', models.CharField(max_length=30, null=True, verbose_name='신문사')),
                ('content', models.TextField(max_length=builtins.max, verbose_name='내용')),
                ('upload_date', models.CharField(max_length=30, null=True, verbose_name='뉴스 날자')),
                ('craw_date', models.DateTimeField(auto_now=True, verbose_name='크롤링 날자')),
                ('words', models.TextField(max_length=builtins.max, verbose_name='단어조각')),
            ],
            options={
                'verbose_name': '환율 기사',
                'verbose_name_plural': '환율 기사',
                'db_table': 'NaverNews',
            },
        ),
    ]
