# Generated by Django 3.1.3 on 2020-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCB', '0004_auto_20201124_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSTMInfo',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=30, verbose_name='날짜')),
                ('dollar_close', models.FloatField(null=True, verbose_name='달러 종가')),
            ],
            options={
                'verbose_name': 'LSTM예측테이블',
                'verbose_name_plural': 'LSTM예측테이블',
                'db_table': 'LSTM_Info',
            },
        ),
    ]
