# Generated by Django 3.1.3 on 2020-11-24 09:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_name', models.CharField(max_length=30, verbose_name='이름')),
                ('user_password', models.CharField(max_length=30, verbose_name='패스워드')),
                ('user_pwcheck', models.CharField(max_length=30, verbose_name='패스워드 체크')),
                ('user_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('user_emailcheck', models.BooleanField(default=False, verbose_name='이메일 체크')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'LMG 유저',
                'verbose_name_plural': 'LMG 유저',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.BooleanField(default=False)),
                ('benefits', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=500, verbose_name='탈퇴이유')),
            ],
            options={
                'verbose_name': '회원 탈퇴',
                'verbose_name_plural': '회원 탈퇴',
                'db_table': 'Withdrawal',
            },
        ),
        migrations.CreateModel(
            name='User_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gieob', models.BooleanField(default=False)),
                ('kookmin', models.BooleanField(default=False)),
                ('hana', models.BooleanField(default=False)),
                ('suhyup', models.BooleanField(default=False)),
                ('nonghyup', models.BooleanField(default=False)),
                ('woori', models.BooleanField(default=False)),
                ('standard', models.BooleanField(default=False)),
                ('citi', models.BooleanField(default=False)),
                ('daegu', models.BooleanField(default=False)),
                ('busan', models.BooleanField(default=False)),
                ('jeju', models.BooleanField(default=False)),
                ('jeonbug', models.BooleanField(default=False)),
                ('gyeongnam', models.BooleanField(default=False)),
                ('shinhan', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주거래 은행',
                'verbose_name_plural': '주거래 은행',
                'db_table': 'User_bank',
            },
        ),
    ]
