# Generated by Django 3.1.3 on 2020-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMGUser',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('user_pwconfirm', models.CharField(max_length=30, verbose_name='비밀번호 확인')),
                ('user_email', models.CharField(max_length=30, verbose_name='이메일')),
                ('user_emailcheck', models.BooleanField(default=False, verbose_name='이메일 체크')),
            ],
            options={
                'verbose_name': 'LMG 유저',
                'verbose_name_plural': 'LMG 유저',
                'db_table': 'LMG_User',
            },
        ),
        migrations.CreateModel(
            name='User_bank',
            fields=[
                ('user_id_bank', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='아이디')),
                ('gieob', models.BooleanField(default=False)),
                ('kookmin', models.BooleanField(default=False)),
                ('hana', models.BooleanField(default=False)),
                ('suhyup', models.BooleanField(default=False)),
                ('nonghyup', models.BooleanField(default=False)),
                ('woori', models.BooleanField(default=False)),
                ('standard', models.BooleanField(default=False)),
                ('citi', models.BooleanField(default=False)),
                ('daegu', models.BooleanField(default=False)),
                ('busan', models.BooleanField(default=False)),
                ('jeju', models.BooleanField(default=False)),
                ('jeonbug', models.BooleanField(default=False)),
                ('gyeongnam', models.BooleanField(default=False)),
                ('shinhan', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '주거래 은행',
                'verbose_name_plural': '주거래 은행',
                'db_table': 'User_bank',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.BooleanField(default=False)),
                ('benefits', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=500, verbose_name='탈퇴이유')),
            ],
            options={
                'verbose_name': '회원 탈퇴',
                'verbose_name_plural': '회원 탈퇴',
                'db_table': 'Withdrawal',
            },
        ),
    ]
