# Generated by Django 3.1.3 on 2020-11-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.BooleanField(default=False)),
                ('benefits', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=500, verbose_name='탈퇴이유')),
            ],
            options={
                'verbose_name': '회원 탈퇴',
                'verbose_name_plural': '회원 탈퇴',
                'db_table': 'Withdrawal',
            },
        ),
        migrations.CreateModel(
            name='User_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gieob', models.BooleanField(default=False)),
                ('kookmin', models.BooleanField(default=False)),
                ('hana', models.BooleanField(default=False)),
                ('suhyup', models.BooleanField(default=False)),
                ('nonghyup', models.BooleanField(default=False)),
                ('woori', models.BooleanField(default=False)),
                ('standard', models.BooleanField(default=False)),
                ('citi', models.BooleanField(default=False)),
                ('daegu', models.BooleanField(default=False)),
                ('busan', models.BooleanField(default=False)),
                ('jeju', models.BooleanField(default=False)),
                ('jeonbug', models.BooleanField(default=False)),
                ('gyeongnam', models.BooleanField(default=False)),
                ('shinhan', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주거래 은행',
                'verbose_name_plural': '주거래 은행',
                'db_table': 'User_bank',
            },
        ),
    ]
