# Generated by Django 3.1.3 on 2020-11-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_bank_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
    ]
