# Generated by Django 3.1.3 on 2020-11-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201124_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_pwcheck',
        ),
    ]
