# Generated by Django 3.1.3 on 2020-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_user_pwcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='other',
            field=models.CharField(max_length=500, null=True, verbose_name='탈퇴이유'),
        ),
    ]
